### ISSUE TITLE
A change suggestion on example in readme.

### ISSUE THREAD

**Issue by thinksource** [alanning/meteor-roles#178]
I try to use the example code of master to build new users in my app.
```
var users=[{username: "admin",email: 'admin@admin.com',verified: true,
				password:"admin123",roles: 'admin'},
				{username: "sheng",email: 'sheng@admin.com',verified: true,
								password:"sheng123",roles: []},
				{username: "test", email: "test@test.com",verified:true,
									password: "test123",roles:[]}
			];

if (Meteor.users.find().count() == 0) {

 _.each(users, function(user){
	 var id;
	 id=Accounts.createUser({
		 username:user.username,
		 email:user.email,
		 verified: true,
		 password:user.password,
		 profile:{name:user.username}
	 });
	 if(user.hasOwnProperty('roles') && user.roles.length>0){

		 Roles.addUsersToRoles(id, user.roles);
	 }
 });
```

It always give me errors unless I find the 2.0 branch and add:
```
Roles.createRole('admin', {unlessExists: true});
```
I think you need to add the createRole function in your example in ReadMe.md.

**Comment by mitar** [comment]
> It always give me errors

Which errors?

**Comment by mitar** [comment]
I made a pull request to 1.0 for this some time ago, but it was not merged: https://github.com/alanning/meteor-roles/pull/145

**Comment by thinksource** [comment]
The error is:

````
W20160205-10:50:41.589(11)? (STDERR)     at server/seed.js:29:1
W20160205-10:50:41.589(11)? (STDERR)     at Array.forEach (native)
W20160205-10:50:41.589(11)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
W20160205-10:50:41.589(11)? (STDERR)     at server/seed.js:18:1
W20160205-10:50:41.590(11)? (STDERR)     at server/seed.js:32:1
W20160205-10:50:41.590(11)? (STDERR)     at G:\work\meteor-starter\.meteor\local\build\programs\server\boot.js:242:10
```

The source code:

```
if (Meteor.users.find().count() == 0) {

 _.each(users, function(user){
     var id;
     id=Accounts.createUser({
         username:user.username,
         email:user.email,
         verified: true,
         password:user.password,
         profile:{name:user.username}
     });
     if(user.hasOwnProperty('roles') && user.roles.length>0){

         Roles.addUsersToRoles(id, user.roles);                               //line 29
     }                                                                                                //line 30
 });                                                                                                 //line 31
};                                                                                                   //line 32
````

**Comment by alanning** [comment]
@thinksource If you change the first entry's roles from `roles: 'admin'` to `roles: ['admin']`, does that make any change?

Can you publish a small repro of this to github so we can reproduce it locally, please?

**Comment by thinksource** [comment]
@alanning 
I fellow your suggestion. The same stuff happens:

```
W20160205-17:04:43.777(11)? (STDERR) Error: After filtering out keys not in the schema, your modifier is now empty
W20160205-17:04:43.778(11)? (STDERR)     at [object Object].doValidate (packages/aldeed_collection2-core/lib/collection2.js:282:1)
W20160205-17:04:43.778(11)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core/lib/collection2.js:83:1)
W20160205-17:04:43.778(11)? (STDERR)     at Object._.extend._updateUserRoles (packages/alanning_roles/roles_common.js:679:1)
W20160205-17:04:43.778(11)? (STDERR)     at Object._.extend.addUsersToRoles (packages/alanning_roles/roles_common.js:145:1)
W20160205-17:04:43.778(11)? (STDERR)     at server/seed.js:29:1
W20160205-17:04:43.778(11)? (STDERR)     at Array.forEach (native)
W20160205-17:04:43.778(11)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
W20160205-17:04:43.778(11)? (STDERR)     at server/seed.js:18:1
W20160205-17:04:43.779(11)? (STDERR)     at server/seed.js:32:1
W20160205-17:04:43.779(11)? (STDERR)     at G:\work\meteor-starter\.meteor\local\build\programs\server\boot.js:242:10
```

I will publish a small repro later after I back to home. Currently I am very busy.

**Comment by thinksource** [comment]
@alanning
This is my small repo:
https://github.com/thinksource/mystarter

change server\seed.js

```
if(Meteor.roles.find().count()==0){
	 Roles.createRole('admin', {unlessExists: true}); //delete this line
}
```
delete the corresponding line and the error will appeal.

**Comment by alanning** [comment]
I cloned your app and removed all files other than `server/seed.js`.  Running the app does not result in an error, whether including that line or not.

I'm going to close this issue for now.  Please re-open once you have uploaded a minimal example which reproduces the error you reported.  (Please make it as small as possible, the mystarter one is quite large.)

**Comment by dvmorris** [comment]
I ran into this issue today, and it ended up being related to customizing the user schema in my app. I had the schema configured incorrectly, like this:
```
  // Add `roles` to your schema if you use the meteor-roles package.
  // Option 1: Object type
  // If you specify that type as Object, you must also specify the
  // `Roles.GLOBAL_GROUP` group whenever you add a user to a role.
  // Example:
  // Roles.addUsersToRoles(userId, ["admin"], Roles.GLOBAL_GROUP);
  // You can't mix and match adding with and without a group since
  // you will fail validation in some cases.
  roles: {
      type: Object,
      optional: true,
      blackbox: true
  },
  // Option 2: [String] type
  // If you are sure you will never need to use role groups, then
  // you can specify [String] as the type
  roles: {
       type: [String],
       optional: true
  },
```

**Comment by derwaldgeist** [comment]
Just wanted to add that for v2 is has to be:

```
  roles: {
    type: Array,
    optional: true
  },
  'roles.$': {
    type: Object,
    blackbox: true
  }
```
