### ISSUE TITLE
Tests do not pass completely

### ISSUE THREAD

**Issue by neilyoung** [alanning/meteor-roles#96]
FAIL
S: mixing group with non-group throws descriptive error
- fail — true - message Cannot apply $addToSet to a non-array field. Field named 'roles' has a non-array type Object in the document _id: "wrkKSo7Huk3oJ3Qcg" - not
- fail — true - message cannot use the part (roles of roles.group2) to traverse the element ({roles: [ "editor", "user" ]}) - not
- fail — true - message Can only apply $pullAll to an array. _id: "J8woTH9vS26EW67cq" has the field roles of non-array type Object - not
- fail — true - message cannot use the part (roles of roles.group1) to traverse the element ({roles: [ "editor", "user" ]}) - not
- exception - message cannot use the part (roles of roles.group1) to traverse the element ({roles: [ "editor", "user" ]})
MongoError: cannot use the part (roles of roles.group1) to traverse the element ({roles: [ "editor", "user" ]})
    at Object.Future.wait (/Users/decades/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
    at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
    at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:678:1)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/mongo/collection.js:575:1)
    at Object._.extend.removeUsersFromRoles (packages/alanning:roles/roles_common.js:242:1)
    at Tinytest.add.expectedErrorMsg (packages/local-test:alanning:roles/tests/server.js:950:1)
    at [object Object].func (packages/tinytest/tinytest.js:636:1)
    at packages/tinytest/tinytest.js:406:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    - - - - -
    at Object.toError (/Users/decades/.meteor/packages/mongo/.1.1.0.1ruc6ua++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /Users/decades/.meteor/packages/mongo/.1.1.0.1ruc6ua++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/collection/core.js:577:27
    at /Users/decades/.meteor/packages/mongo/.1.1.0.1ruc6ua++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1195:7
    at /Users/decades/.meteor/packages/mongo/.1.1.0.1ruc6ua++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1903:9
    at Server.Base._callHandler (/Users/decades/.meteor/packages/mongo/.1.1.0.1ruc6ua++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /Users/decades/.meteor/packages/mongo/.1.1.0.1ruc6ua++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
    at [object Object].MongoReply.parseBody (/Users/decades/.meteor/packages/mongo/.1.1.0.1ruc6ua++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/Users/decades/.meteor/packages/mongo/.1.1.0.1ruc6ua++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/Users/decades/.meteor/packages/mongo/.1.1.0.1ruc6ua++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)

**Comment by alanning** [comment]
Fixed on master.
